# Generated by Django 5.0.6 on 2026-04-27 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nickname', models.CharField(max_length=50)),
                ('slogan', models.CharField(max_length=50)),
                ('foundation_date', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_teams', to='player.player')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_teams', to='player.player')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_teams', to='player.player')),
                ('players', models.ManyToManyField(blank=True, related_name='teams', to='player.player')),
            ],
        ),
    ]
