# Generated by Django 5.0.6 on 2026-04-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='foundation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PlayerProposalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FOLLOWER', 'Follower'), ('PLAYER', 'Player'), ('ADMIN', 'Administration')], default='PLAYER')),
                ('proposal_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_proposals', to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_proposals', to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_date', models.DateField(auto_now_add=True)),
                ('matches_played', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('FOLLOWER', 'Follower'), ('PLAYER', 'Player'), ('ADMIN', 'Administration')], default='FOLLOWER')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='team.team')),
            ],
        ),
    ]
