# Generated by Django 5.0.6 on 2026-04-30 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0002_alter_team_foundation_date_playerproposalteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='followers',
        ),
        migrations.AddField(
            model_name='playerproposalteam',
            name='proposal_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playerproposalteam',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='player.player'),
        ),
        migrations.AlterField(
            model_name='playerproposalteam',
            name='role',
            field=models.CharField(choices=[('FOLLOWER', 'Follower'), ('PLAYER', 'Player'), ('ADMIN', 'Admin')], default='PLAYER', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerproposalteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='team.team'),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='player.player'),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='role',
            field=models.CharField(choices=[('FOLLOWER', 'Follower'), ('PLAYER', 'Player'), ('ADMIN', 'Admin')], default='FOLLOWER', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='team.team'),
        ),

        migrations.AlterUniqueTogether(
            name='playerproposalteam',
            unique_together={('player', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='playerteam',
            unique_together={('player', 'team')},
        ),
    ]
