# Generated by Django 5.0.6 on 2026-05-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_remove_team_followers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="players",
        ),
        migrations.AddField(
            model_name="team",
            name="players",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams",
                through="team.PlayerTeam",
                to="player.player",
            ),
        ),
    ]
