# Generated by Django 5.0.6 on 2026-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_fix_team_players_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
