# Generated by Django 5.0.6 on 2026-05-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='followers',
            new_name='qty_followers',
        ),
    ]
