# Generated by Django 5.0.6 on 2026-05-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_rename_followers_team_qty_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playerteam',
            name='role',
        ),
        migrations.AddField(
            model_name='playerteam',
            name='roles',
            field=models.ManyToManyField(blank=True, to='team.role'),
        ),
    ]
