# Generated by Django 5.0.6 on 2026-05-11 09:06

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("team", "Role")

    roles = [
        "FOLLOWER",
        "PLAYER",
        "ADMIN",
    ]

    for role_name in roles:
        Role.objects.get_or_create(name=role_name)


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0007_role_remove_playerteam_role_playerteam_roles"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
