# Generated by Django 5.0.6 on 2026-05-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0006_rename_followers_team_qty_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='followed_teams',
            field=models.ManyToManyField(blank=True, related_name='followers', to='team.team'),
        ),
    ]
