# Generated by Django 5.0.6 on 2026-05-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
        ('team', '0008_seed_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerachievement',
            name='achievement',
        ),
        migrations.AddField(
            model_name='playerachievement',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='player_owners', to='achievement.achievement'),
        ),
        migrations.CreateModel(
            name='TeamAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('achievements', models.ManyToManyField(blank=True, related_name='team_owners', to='achievement.achievement')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_achievement', to='team.team')),
            ],
        ),
    ]
