# Generated by Django 5.0.6 on 2026-05-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_remove_playerachievement_achievement_and_more'),
        ('player', '0002_player_followed_teams'),
        ('team', '0008_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerachievement',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_achievements', to='achievement.achievement'),
        ),
        migrations.AddField(
            model_name='playerachievement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_achievements', to='achievement.achievement'),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playerachievement',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_achievements', to='player.player'),
        ),
        migrations.AlterField(
            model_name='teamachievement',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_achievements', to='team.team'),
        ),
        migrations.RemoveField(
            model_name='playerachievement',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='playerachievement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='playerachievement',
            unique_together={('player', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='teamachievement',
            unique_together={('team', 'achievement')},
        ),
    ]
