# Generated by Django 5.0.6 on 2026-05-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_alter_playerachievement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
