# Generated by Django 5.0.6 on 2026-06-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0005_alter_playerachievement_achievement_alter_teamachievement_achievement'),
        ('player', '0002_player_followed_teams'),
        ('team', '0008_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTeamAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team_achievements', to='achievement.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team_achievements', to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team_achievements', to='team.team')),
            ],
            options={
                'unique_together': {('player', 'team', 'achievement')},
            },
        ),
    ]
